hospital/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path("home/", views.home, name="home"),
    path("add_doctor/", views.addDoctor, name="addDoc"),
    path("all_doctor/", views.allDoctor, name="allDoc"),
    path("all_patient/", views.allPatients, name="allPatient"),
    path("all_appointment/", views.allAppointments, name="allAppointment"),
    path("update_appointment/<int:id>", views.adminUpdateAppointment, name="updateAppointment"),
    path("delete_appointment/<int:id>", views.deleteAppointment, name="deleteAppointment"),
    path("approve_appointment/<int:id>", views.approveAppointment, name="approveAppointment"),
    path("doctor_appointments/", views.doctorAppointments, name="docAppointment"),
    path("doctor_appointment_complete/<int:id>", views.completeAppointment, name="docAptComplete"),
    path("doctor_patients/<int:id>", views.doctorPatients, name="docPatient"),
    path("doctor_profile/<int:id>", views.doctorProfile, name="docProfile"),
    path("appointment/", views.add_appointment, name="appointment"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="hospital/password_reset_done.html"), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="hospital/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name="hospital/password_reset_complete.html"), name='password_reset_complete'),
    path("password_reset", views.password_reset_request, name="password_reset")
]

hspmgmt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("hospital.urls")),
    path("", include("patient.urls")),
]

hospital/models.py
from django.db import models
from django.contrib.auth.models import User
from patient.models import Patient
from django.core.validators import MinLengthValidator
from .fields import MinuteDateTimeField


class Doctor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=10, validators=[MinLengthValidator(10)])
    specialization = models.CharField(max_length=50)
    qualification = models.CharField(max_length=50)
    address = models.CharField(max_length=50)
    availability = models.BooleanField(null=True)

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}"


class Appointment(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    appointment_Date = MinuteDateTimeField(unique=True)
    approve = models.BooleanField(null=True)
    complete = models.BooleanField(null=True)
    created = models.DateTimeField(auto_now_add=True)

hospital/forms.py
from django.forms import ModelForm, CheckboxInput
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from datetimewidget.widgets import DateTimeWidget
from .models import Doctor, Appointment


dateTimeOptions = {
    'format': 'dd/mm/yyyy HH:ii P',
    'autoclose': True,
    'showMeridian': True,
    'minuteStep': 30,
    'daysOfWeekDisabled': 6,
}

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']
        labels = {'email': 'E-mail'}


class DoctorUserForm(ModelForm):

    class Meta:
        model = Doctor
        fields = ['phone', 'specialization', 'qualification', 'address', 'availability']
        widgets = {
            'availability': CheckboxInput(attrs={'class': 'required avl'}),
        }
        labels = {'availability': 'Available'}


class AppointmentForm(ModelForm):
    class Meta:
        model = Appointment
        fields = ['doctor', 'appointment_Date']
        widgets = {
            'appointment_Date': DateTimeWidget(options=dateTimeOptions, usel10n=True),
        }

hospital/views.py
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.models import User, Permission
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import send_mail, BadHeaderError
from django.db.models import Q
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from .models import Doctor, Appointment
from patient.models import Patient
from .forms import AppointmentForm, DoctorUserForm, CreateUserForm
from django.contrib import messages


# Create your views here.
@login_required()
def home(request):
    if request.user.is_superuser:
        all_appointments = Appointment.objects.all().order_by('-id')
        return render(request, "hospital/adminAllApt.html", {'appointments': all_appointments})
    elif request.user.is_staff and not request.user.is_superuser:
        dr = request.user.id
        drAppointments = Appointment.objects.filter(doctor__user_id=dr).order_by('-id')
        return render(request, "hospital/doctorAppointments.html", {'appointments': drAppointments})
    else:
        messages.success(request, "Not Authorized")
        return redirect('logout')


def allDoctor(request):
    if request.user.is_superuser:
        all_doc = Doctor.objects.all().order_by('-id')
        return render(request, "hospital/adminAllDoctor.html", {'doctors': all_doc})
    else:
        return redirect("logout")


def allPatients(request):
    if request.user.is_superuser:
        all_patients = Patient.objects.all().order_by('-id')
        return render(request, "hospital/adminAllPatient.html", {'patients': all_patients})
    else:
        return redirect("logout")


def allAppointments(request):
    if request.user.is_superuser:
        all_appointments = Appointment.objects.all().order_by('-id')
        return render(request, "hospital/adminAllApt.html", {'appointments': all_appointments})
    else:
        return redirect("logout")


def adminUpdateAppointment(request, id):
    if request.user.is_superuser:
        if request.method == "POST":
            apt = Appointment.objects.get(pk=id)
            form = AppointmentForm(request.POST, instance=apt)
            dr_id = form.data['doctor']
            dr = Doctor.objects.get(pk=dr_id)
            if form.is_valid():
                if dr.availability:
                    form.save()
                    messages.success(request, "Appointment Updated")
                    return redirect("allAppointment")
                else:
                    messages.success(request, "Doctor not Available")
            else:
                messages.success(request, "Appointment already exist please select other time or date")
        else:
            apt = Appointment.objects.get(pk=id)
            form = AppointmentForm(instance=apt)
        return render(request, "hospital/adminAppointmentUpdate.html", {"form": form})
    else:
        return redirect("logout")


@login_required()
def addDoctor(request):
    if request.user.is_superuser:
        if request.method == "POST":
            form = CreateUserForm(request.POST)
            dform = DoctorUserForm(request.POST)

            if form.is_valid() and dform.is_valid():
                form.instance.is_staff = True
                user = form.save()
                dr = dform.save(commit=False)
                permission = Permission.objects.get(name='Can view doctor')
                user.user_permissions.add(permission)
                dr.user = user
                dr.save()

                messages.success(request, "Doctor Registered Successfully")
                return redirect("allDoc")
        else:
            form = CreateUserForm()
            dform = DoctorUserForm()
        return render(request, "hospital/adminAddDoctor.html", {"form": form, "dform": dform})
    else:
        return redirect("logout")


def doctorAppointments(request):
    if request.user.is_staff and not request.user.is_superuser:
        dr = request.user.id
        drAppointments = Appointment.objects.filter(doctor__user_id=dr).order_by('-id')
        return render(request, "hospital/doctorAppointments.html", {'appointments': drAppointments})
    else:
        return redirect("logout")


def doctorProfile(request, id):
    if request.user.is_staff and not request.user.is_superuser:
        if request.method == "POST":
            ur = User.objects.get(pk=id)
            dr = Doctor.objects.get(user_id=id)
            form = CreateUserForm(request.POST, instance=ur)
            dform = DoctorUserForm(request.POST, instance=dr)

            if form.is_valid() and dform.is_valid():
                user = form.save()
                doc = dform.save(commit=False)
                doc.user = user
                doc.save()
                return redirect('/')
        else:
            ur = User.objects.get(pk=id)
            dr = Doctor.objects.get(user_id=id)
            form = CreateUserForm(instance=ur)
            dform = DoctorUserForm(instance=dr)
        return render(request, "hospital/doctorProfile.html", {"form": form, "dform": dform})
    else:
        return redirect("logout")


def deleteAppointment(request, id):
    if request.user.is_superuser:
        if request.method == "POST":
            apt = Appointment.objects.get(pk=id)
            apt.delete()
            messages.success(request, "Appointment Deleted")
            return HttpResponseRedirect("/")
    else:
        messages.success(request, "Don't have permission to delete the appointment")


@login_required()
def add_appointment(request):
    if request.method == 'POST':
        form = AppointmentForm(request.POST)
        dr_id = form.data['doctor']
        dr = Doctor.objects.get(pk=dr_id)
        if form.is_valid():
            if dr.availability:
                my_p = Patient.objects.get(user=request.user)
                form = form.save(commit=False)
                form.patient = my_p
                form.save()

                messages.success(request, "Appointment Added")
                return redirect('pAppointment')
            else:
                messages.success(request, "Doctor not Available")
        else:
            messages.success(request, "Appointment already exist please select other time or date")
    else:
        form = AppointmentForm()
    return render(request, "hospital/addAppointment.html", {"form": form})


def approveAppointment(request, id):
    if request.user.is_staff or request.user.is_superuser:
        if request.method == "POST":
            apt = Appointment.objects.get(pk=id)
            apt.approve = True
            apt.save()
            messages.success(request, "Appointment Approved")
            if request.user.is_superuser:
                return redirect('allAppointment')
            else:
                return redirect('docAppointment')
    else:
        messages.success(request, "Don't have permission to approve the appointment")


def completeAppointment(request, id):
    if request.user.is_staff and not request.user.is_superuser:
        if request.method == "POST":
            apt = Appointment.objects.get(pk=id)
            apt.complete = True
            apt.save()
            messages.success(request, "Appointment Complete")
            return redirect('docAppointment')
    else:
        messages.success(request, "You don't have permission to complete the appointment  ")
        return redirect('docAppointment')


def doctorPatients(request, id):
    patients = []
    if request.user.is_staff and not request.user.is_superuser:
        dr = Doctor.objects.get(user_id=id)
        apts = Appointment.objects.values_list('patient_id', flat=True).filter(doctor_id=dr)
        patientId = set(apts)
        for pt in patientId:
            patients.append(Patient.objects.get(pk=pt))
        return render(request, "hospital/doctorPatients.html", {'patients': patients})
    else:
        return redirect("logout")


def password_reset_request(request):
    if request.method == "POST":
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data['email']
            associated_users = User.objects.filter(Q(email=data))
            if associated_users.exists():
                for user in associated_users:
                    subject = "Password Reset Requested"
                    email_template_name = "hospital/password_reset_email.txt"
                    c = {
                        "email": user.email,
                        'domain': '127.0.0.1:8000',
                        'site_name': 'Website',
                        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                        "user": user,
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                    }
                    email = render_to_string(email_template_name, c)
                    try:
                        send_mail(subject, email, 'admin@example.com', [user.email], fail_silently=False)
                    except BadHeaderError:
                        return HttpResponse('Invalid header found.')
                    return redirect("/password_reset/done/")
            messages.success(request, 'An invalid email has been entered.')
    password_reset_form = PasswordResetForm()
    return render(request=request, template_name="hospital/password_reset.html",
                  context={"password_reset_form": password_reset_form})

hospital/templates/hospital/addAppointment.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Add Department{% endblock %}
{% block content %}

{% if request.user.is_authenticated %}
<nav class="navbar sticky-top" style="background-color:#d18d10">
  <span class="navbar-brand">{{ request.user.username }}</span>
    <div class="navbar-nav navbar-expand-lg justify-content-end nav">
        <a class="nav-item nav-link btn btn-md px-1" href="{% url 'appointment' %}" role="button">Add Appointment</a>
        <a class="nav-item nav-link btn btn-md px-1" href="{% url 'pAppointment' %}" role="button">View Appointments</a>
        <a class="nav-item nav-link btn btn-md px-1" href="{% url 'pProfile' request.user.id %}" role="button">Profile</a>
        <a class="nav-item nav-link btn btn-md px-1" href="{% url 'logout' %}" role="button">Logout</a>
    </div>
</nav>
{% endif %}

  <div class="card shadow-lg p-4 mt-5 w-50 mx-auto">
    <div class="card-body">
      <h5 class="card-title">Add Appointment</h5>
      <form class="card-text" method="POST">{% csrf_token %}
        {{ form|crispy }}
<!--      <button class="btn btn-outline-info" type="submit">Submit</button>-->
        <input class="btn btn-outline-info" id="submit" type="submit" value="Submit">
      </form>
    </div>
  </div>

{% endblock %}

hospital/templates/hospital/adminAddDoctor.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Add Doctor{% endblock %}
{% block content %}
{% if request.user.is_authenticated %}
<style>
#id_availability {
  margin-left: 80px;
}
</style>
<nav class="navbar sticky-top" style="background-color:#d18d10">
  <span class="navbar-brand">{{ request.user.username }}</span>

    <div class="navbar-nav navbar-expand-lg justify-content-end nav">
        <a class="nav-item nav-link btn btn-md px-1" href="{% url 'addDoc' %}" role="button">Add Doctor</a>
        <a class="nav-item nav-link btn btn-md px-1" href="{% url 'allDoc' %}" role="button">View Doctor</a>
        <a class="nav-item nav-link btn btn-md px-1" href="{% url 'allPatient' %}" role="button">View Patients</a>
        <a class="nav-item nav-link btn btn-md px-1" href="{% url 'allAppointment' %}" role="button">View Appointments</a>
        <a class="nav-item nav-link btn btn-md px-1" href="{% url 'logout' %}" role="button">Logout</a>
    </div>
</nav>

<div class="container-fluid" style="background-origin: origin;">
  <div class="card shadow-lg p-4 w-50 mx-auto" style="margin-top:10px">
    <div class="card-body">
      <h5 class="card-title">Doctor Registration</h5>
      <form class="card-text" method="POST" enctype="multipart/form-data">{% csrf_token %}
        {{ form|crispy }}
        {{ dform|crispy }}
      <button class="btn btn-outline-info" type="submit">Submit</button>
      </form>
    </div>
  </div>
</div>
{% endif %}
{% endblock %}

hospital/templates/hospital/adminAllApt.html
{% extends 'base.html' %}
{% block title %}Appointments{% endblock %}
{% block content %}

{% if request.user.is_authenticated %}
<nav class="navbar sticky-top" style="background-color:#d18d10">
  <span class="navbar-brand">{{ request.user.username }}</span>
    <div class="navbar-nav navbar-expand-lg justify-content-end nav">
        <a class="nav-item nav-link btn btn-md px-1" href="{% url 'addDoc' %}" role="button">Add Doctor</a>
        <a class="nav-item nav-link btn btn-md px-1" href="{% url 'allDoc' %}" role="button">View Doctor</a>
        <a class="nav-item nav-link btn btn-md px-1" href="{% url 'allPatient' %}" role="button">View Patients</a>
        <a class="nav-item nav-link btn btn-md px-1" href="{% url 'allAppointment' %}" role="button">View Appointments</a>
        <a class="nav-item nav-link btn btn-md px-1" href="{% url 'logout' %}" role="button">Logout</a>
    </div>
</nav>

<div class="card mx-auto shadow-lg p-4 mb-4 bg-white w-75">
  <div class="card-body">
      <h2>Appointments</h2>
      <hr><p class="card-text">
      <table class="table-bordered table">
        <tr>
            <th>Patient Name</th>
            <th>Doctor Name</th>
            <th>Specialist</th>
            <th>Appointment Date</th>
            <th>Action</th>
        </tr>
        {% for appointment in appointments %}
        <tr>
            <th>{{ appointment.patient }}</th>
            <th>{{ appointment.doctor }}</th>
            <th>{{ appointment.doctor.specialization }}</th>
            <th>{{ appointment.appointment_Date }}</th>
            <th style="">
                {% if appointment.approve == 1 %}
                        <input type="submit" class="btn btn-outline-primary disabled p-2 m-1" value="Approved">
                    {% else %}
                <a href="{% url 'updateAppointment' appointment.id %}" class="btn btn-primary p-2 m-1" role="button">Edit</a>
                    <form action="{% url 'approveAppointment' appointment.id %}" method="post">{% csrf_token %}
                        <input type="submit" class="btn btn-success p-2 m-1" value="Approve">
                    </form>
                <form action="{% url 'deleteAppointment' appointment.id %}" method="post">{% csrf_token %}
                    <input type="submit" class="btn btn-danger p-2 m-1" value="Delete">
                </form>
                {% endif %}
            </th>
        </tr>
        {% endfor %}
        </table>
    </p>
  </div>
</div>
{% endif %}


<div class="card mx-auto shadow-lg p-4 mb-4 bg-white w-75">
  <div class="card-body">
      <h2>Appointments History</h2>
      <hr><p class="card-text">
      <table class="table-bordered table">
        <tr>
            <th>Doctor</th>
            <th>Specialist</th>
            <th>Appointment Date</th>
        </tr>
        {% for appointment in appointments %}
            {% if appointment.complete == 1 %}
                <tr>
                    <th>{{ appointment.doctor }}</th>
                    <th>{{ appointment.doctor.specialization }}</th>
                    <th>{{ appointment.appointment_Date }}</th>
                </tr>
            {% endif %}
        {% endfor %}
        </table>
    </p>
  </div>
</div>


{% endblock %}

hospital/templates/hospital/adminAllPatient.html
{% extends 'base.html' %}
{% block title %}Patients{% endblock %}
{% block content %}

{% if request.user.is_authenticated %}
<nav class="navbar sticky-top" style="background-color:#d18d10">
  <span class="navbar-brand">{{ request.user.username }}</span>
    <div class="navbar-nav navbar-expand-lg justify-content-end nav">
        <a class="nav-item nav-link btn btn-md px-1" href="{% url 'addDoc' %}" role="button">Add Doctor</a>
        <a class="nav-item nav-link btn btn-md px-1" href="{% url 'allDoc' %}" role="button">View Doctor</a>
        <a class="nav-item nav-link btn btn-md px-1" href="{% url 'allPatient' %}" role="button">View Patients</a>
        <a class="nav-item nav-link btn btn-md px-1" href="{% url 'allAppointment' %}" role="button">View Appointments</a>
        <a class="nav-item nav-link btn btn-md px-1" href="{% url 'logout' %}" role="button">Logout</a>
    </div>
</nav>

<div class="card mx-auto shadow-lg p-4 mb-4 bg-white w-75">
  <div class="card-body">
      <h2>Patients
      <a class="btn btn-md px-3 mr-5 btn-primary float-right" href="{% url 'register' %}" role="button">Add Patient</a></h2></h2>
      <hr><p class="card-text">
        <table class="table-bordered table">
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Address</th>
                <th>Phone</th>
                <th>Email</th>
                <th>Gender</th>
                <th>Age</th>
            </tr>
          {% for patient in patients %}
            <tr>
                <th>{{ patient.user.id }}</th>
                <th>{{ patient }}</th>
                <th>{{ patient.address }}</th>
                <th>{{ patient.phone }}</th>
                <th>{{ patient.user.email }}</th>
                <th>{{ patient.gender }}</th>
                <th>{{ patient.age }}</th>
            </tr>
          {% endfor %}
        </table>
        </p>
  </div>
</div>
{% endif %}


{% endblock %}

hospital/templates/hospital/adminAppointmentUpdate.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Add Department{% endblock %}
{% block content %}

{% if request.user.is_authenticated %}
<nav class="navbar sticky-top" style="background-color:#d18d10">
  <span class="navbar-brand">{{ request.user.username }}</span>
    <div class="navbar-nav navbar-expand-lg justify-content-end nav">
        <a class="nav-item nav-link btn btn-md px-1" href="{% url 'addDoc' %}" role="button">Add Doctor</a>
        <a class="nav-item nav-link btn btn-md px-1" href="{% url 'allDoc' %}" role="button">View Doctor</a>
        <a class="nav-item nav-link btn btn-md px-1" href="{% url 'allPatient' %}" role="button">View Patients</a>
        <a class="nav-item nav-link btn btn-md px-1" href="{% url 'allAppointment' %}" role="button">View Appointments</a>
        <a class="nav-item nav-link btn btn-md px-1" href="{% url 'logout' %}" role="button">Logout</a>
    </div>
</nav>


  <div class="card shadow-lg p-4 mt-5 w-50 mx-auto">
    <div class="card-body">
      <h5 class="card-title">Update Appointment</h5>
      <form class="card-text" method="POST">{% csrf_token %}
        {{ form|crispy }}
<!--      <button class="btn btn-outline-info" type="submit">Submit</button>-->
        <input class="btn btn-outline-info" id="submit" type="submit" value="Submit">
      </form>
    </div>
  </div>
{% endif %}
{% endblock %}

hospital/templates/hospital/doc.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block content %}

<!--<h1>Home Page</h1>-->


<form  action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
  <input id="datetimeinput" type="text">
    <input id="submit" type="submit" value="Submit">
    </form>

<script>
      $("#datetimeinput").datetimepicker({
            format: 'Y-m-d H:i'
      });

  </script>
{% endblock %}

<!--<!doctype html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--  <meta charset="utf-8">-->
<!--  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">-->
<!--  <title>Static Example</title>-->

<!--  &lt;!&ndash; jQuery &ndash;&gt;-->
<!--  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>-->

<!--  &lt;!&ndash; XDSoft DateTimePicker &ndash;&gt;-->
<!--  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />-->
<!--  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>-->
<!--</head>-->
<!--<body>-->

<!--  <input id="datetimeinput" type="text">-->

<!--  <script>-->
<!--      $("#datetimeinput").datetimepicker({-->
<!--            format: 'Y-m-d H:i'-->
<!--      });-->

<!--  </script>-->

<!--</body>-->
<!--</html>-->

hospital/templates/hospital/doctorPatients.html
{% extends 'base.html' %}
{% block title %}Patients{% endblock %}
{% block content %}

{% if request.user.is_authenticated %}
<nav class="navbar sticky-top" style="background-color:#d18d10">
  <span class="navbar-brand">{{ request.user.username }}</span>
    <div class="navbar-nav navbar-expand-lg justify-content-end nav">
        <a class="nav-item nav-link btn btn-md px-1" href="{% url 'docAppointment' %}" role="button">My Appointments</a>
        <a class="nav-item nav-link btn btn-md px-1" href="{% url 'docPatient' request.user.id %}" role="button">My Patients</a>
        <a class="nav-item nav-link btn btn-md px-1" href="{% url 'docProfile' request.user.id %}" role="button">Profile</a>
        <a class="nav-item nav-link btn btn-md px-1" href="{% url 'logout' %}" role="button">Logout</a>
    </div>
</nav>

<div class="card mx-auto shadow-lg p-4 mb-4 bg-white w-75">
  <div class="card-body">
      <h2>Patients</h2>
      <hr><p class="card-text">
      <table class="table-bordered table">
        <tr>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Address</th>
                <th>Phone</th>
                <th>Email</th>
                <th>Gender</th>
                <th>Age</th>
            </tr>
          {% for patient in patients %}
            <tr>
                <th>{{ patient.user.id }}</th>
                <th>{{ patient }}</th>
                <th>{{ patient.address }}</th>
                <th>{{ patient.phone }}</th>
                <th>{{ patient.user.email }}</th>
                <th>{{ patient.gender }}</th>
                <th>{{ patient.age }}</th>
            </tr>
          {% endfor %}
        </table>
    </p>
  </div>
</div>
{% endif %}


{% endblock %}

hospital/templates/hospital/doctorProfile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Update Doctor{% endblock %}

{% block content %}
<style>
#id_availability {
  margin-left: 80px;
}
</style>

{% if request.user.is_authenticated %}
<nav class="navbar sticky-top" style="background-color:#d18d10">
  <span class="navbar-brand">{{ request.user.username }}</span>
    <div class="navbar-nav navbar-expand-lg justify-content-end nav">
        <a class="nav-item nav-link btn btn-md px-1" href="{% url 'docAppointment' %}" role="button">My Appointments</a>
        <a class="nav-item nav-link btn btn-md px-1" href="{% url 'docPatient' request.user.id %}" role="button">My Patients</a>
        <a class="nav-item nav-link btn btn-md px-1" href="{% url 'docProfile' request.user.id %}" role="button">Profile</a>
        <a class="nav-item nav-link btn btn-md px-1" href="{% url 'logout' %}" role="button">Logout</a>
    </div>
</nav>

  <div class="card shadow-lg p-4 mt-5 w-50 mx-auto">
    <div class="card-body">
      <h3 class="card-title">Update Profile</h3>
      <form class="card-text" method="POST" enctype="multipart/form-data">{% csrf_token %}
        {{ form|crispy }}
          {{ dform|crispy }}
      <button class="btn btn-outline-info" type="submit">Update</button>
      </form>
    </div>
  </div>
{% endif %}
{% endblock %}

hospital/templates/hospital/password_reset.html
{% extends 'base.html' %}

{% block content %}

	{% load crispy_forms_tags %}

	<!--Reset Password-->
	<div class="container p-5">
  	 	<h2 class="font-weight-bold mt-3">Reset Password</h2>
		<hr>
		<p>Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.</p>
        <form method="POST">
            {% csrf_token %}
            {{ password_reset_form|crispy }}
            <button class="btn btn-primary" type="submit">Send email</button>
			 <a class="nav-item nav-link btn btn-md btn-primary px-4 ml-1" href="{% url 'login' %}" role="button">Back</a>
        </form>
  	</div>

{% endblock %}

hospital/templates/hospital/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}

  <!--Password Reset Complete-->
    <div class="container p-4">
	    <h2 class="font-weight-bold mt-3">Password reset complete</h2>
		<hr>
        <p>Your password has been set. You may go ahead and log in now.</p>
        <a href="/" class="btn btn-primary">Log in</a>
    </div>

{% endblock %}